"""add chat sessions and messages tables

Revision ID: 9f57ba746e2b
Revises: 5422228f533c
Create Date: 2026-05-24 21:37:35.237431
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9f57ba746e2b'
down_revision: Union[str, None] = '5422228f533c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('pharmacist_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_patient_id'), 'chat_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_pharmacist_id'), 'chat_sessions', ['pharmacist_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_result', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_index(op.f('idx_thai_fda_reg'), table_name='thai_fda_drugs')
    op.drop_index(op.f('idx_thai_fda_search'), table_name='thai_fda_drugs', postgresql_using='gin')
    op.drop_table('thai_fda_drugs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thai_fda_drugs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thai_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('english_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('drug_category', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('dosage_form', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'คงอยู่'::character varying"), autoincrement=False, nullable=True),
    sa.Column('search_term', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('thai_fda_drugs_pkey'))
    )
    op.create_index(op.f('idx_thai_fda_search'), 'thai_fda_drugs', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_thai_fda_reg'), 'thai_fda_drugs', ['registration_number'], unique=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_pharmacist_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_patient_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
