"""add ndc_products and ndc_packages tables

Revision ID: e2c554d781c5
Revises: ff6edb4e030c
Create Date: 2026-05-23 19:37:57.209037
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e2c554d781c5'
down_revision: Union[str, None] = 'ff6edb4e030c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ndc_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_ndc', sa.String(length=20), nullable=False),
    sa.Column('ndc_package_code', sa.String(length=20), nullable=False),
    sa.Column('package_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ndc_package_code')
    )
    op.create_index('idx_ndc_package_code', 'ndc_packages', ['ndc_package_code'], unique=False)
    op.create_index(op.f('ix_ndc_packages_product_ndc'), 'ndc_packages', ['product_ndc'], unique=False)
    op.create_table('ndc_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_ndc', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('brand_name', sa.String(length=500), nullable=True),
    sa.Column('brand_name_suffix', sa.String(length=200), nullable=True),
    sa.Column('generic_name', sa.Text(), nullable=True),
    sa.Column('dosage_form', sa.String(length=200), nullable=True),
    sa.Column('route', sa.String(length=200), nullable=True),
    sa.Column('marketing_category', sa.String(length=100), nullable=True),
    sa.Column('application_number', sa.String(length=50), nullable=True),
    sa.Column('labeler_name', sa.String(length=500), nullable=True),
    sa.Column('substance_name', sa.Text(), nullable=True),
    sa.Column('strength', sa.Text(), nullable=True),
    sa.Column('strength_unit', sa.Text(), nullable=True),
    sa.Column('pharm_classes', sa.Text(), nullable=True),
    sa.Column('dea_schedule', sa.String(length=10), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ndc_product_brand', 'ndc_products', ['brand_name'], unique=False)
    op.create_index('idx_ndc_product_generic', 'ndc_products', ['generic_name'], unique=False)
    op.create_index('idx_ndc_product_search', 'ndc_products', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ndc_products_product_ndc'), 'ndc_products', ['product_ndc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ndc_products_product_ndc'), table_name='ndc_products')
    op.drop_index('idx_ndc_product_search', table_name='ndc_products', postgresql_using='gin')
    op.drop_index('idx_ndc_product_generic', table_name='ndc_products')
    op.drop_index('idx_ndc_product_brand', table_name='ndc_products')
    op.drop_table('ndc_products')
    op.drop_index(op.f('ix_ndc_packages_product_ndc'), table_name='ndc_packages')
    op.drop_index('idx_ndc_package_code', table_name='ndc_packages')
    op.drop_table('ndc_packages')
    # ### end Alembic commands ###
