"""initial schema: users and rxnorm tables

Revision ID: ff6edb4e030c
Revises: 
Create Date: 2026-05-23 19:12:20.153397
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ff6edb4e030c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rxn_concepts',
    sa.Column('rxcui', sa.Integer(), nullable=False),
    sa.Column('tty', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('suppress', sa.String(length=1), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('rxcui')
    )
    op.create_index('idx_rxn_concepts_rxcui_tty', 'rxn_concepts', ['rxcui', 'tty'], unique=False)
    op.create_index('idx_rxn_concepts_search', 'rxn_concepts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_rxn_concepts_tty'), 'rxn_concepts', ['tty'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pharmacist', 'technician', name='userrole'), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('rxn_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rxcui', sa.Integer(), nullable=False),
    sa.Column('atn', sa.String(length=100), nullable=False),
    sa.Column('atv', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rxcui'], ['rxn_concepts.rxcui'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rxn_attr_atn', 'rxn_attributes', ['atn'], unique=False)
    op.create_index('idx_rxn_attr_atn_atv', 'rxn_attributes', ['atn', 'atv'], unique=False)
    op.create_index('idx_rxn_attr_rxcui', 'rxn_attributes', ['rxcui'], unique=False)
    op.create_table('rxn_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rxcui1', sa.Integer(), nullable=False),
    sa.Column('rel', sa.String(length=10), nullable=False),
    sa.Column('rela', sa.String(length=60), nullable=True),
    sa.Column('rxcui2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rxcui1'], ['rxn_concepts.rxcui'], ),
    sa.ForeignKeyConstraint(['rxcui2'], ['rxn_concepts.rxcui'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rxn_rel_rela', 'rxn_relationships', ['rela'], unique=False)
    op.create_index('idx_rxn_rel_rxcui1', 'rxn_relationships', ['rxcui1'], unique=False)
    op.create_index('idx_rxn_rel_rxcui1_rela', 'rxn_relationships', ['rxcui1', 'rela'], unique=False)
    op.create_index('idx_rxn_rel_rxcui2', 'rxn_relationships', ['rxcui2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rxn_rel_rxcui2', table_name='rxn_relationships')
    op.drop_index('idx_rxn_rel_rxcui1_rela', table_name='rxn_relationships')
    op.drop_index('idx_rxn_rel_rxcui1', table_name='rxn_relationships')
    op.drop_index('idx_rxn_rel_rela', table_name='rxn_relationships')
    op.drop_table('rxn_relationships')
    op.drop_index('idx_rxn_attr_rxcui', table_name='rxn_attributes')
    op.drop_index('idx_rxn_attr_atn_atv', table_name='rxn_attributes')
    op.drop_index('idx_rxn_attr_atn', table_name='rxn_attributes')
    op.drop_table('rxn_attributes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rxn_concepts_tty'), table_name='rxn_concepts')
    op.drop_index('idx_rxn_concepts_search', table_name='rxn_concepts', postgresql_using='gin')
    op.drop_index('idx_rxn_concepts_rxcui_tty', table_name='rxn_concepts')
    op.drop_table('rxn_concepts')
    # ### end Alembic commands ###
