"""
Curated dosing reference for common drugs.
Sources: FDA labels, clinical guidelines, pharmacology references.

Each entry contains structured dosing data for calculation.
Units: mg for dose, mg/kg for weight-based, hours for frequency.
"""

DOSING_REFERENCE: dict[str, dict] = {
    "paracetamol": {
        "generic_name": "acetaminophen (paracetamol)",
        "available_strengths": [125, 250, 325, 500, 650, 1000],
        "unit": "mg",
        "adult": {
            "standard_dose": 500,
            "dose_range": [325, 1000],
            "frequency_hours": 4,
            "min_frequency_hours": 4,
            "max_daily_dose": 4000,
            "max_single_dose": 1000,
            "max_doses_per_day": 6,
            "route": "oral",
            "notes": "Do not exceed 4g/day. Reduce to 2g/day max in liver disease or chronic alcohol use.",
        },
        "pediatric": {
            "dose_per_kg": 15,
            "dose_range_per_kg": [10, 15],
            "frequency_hours": 4,
            "min_frequency_hours": 4,
            "max_daily_dose_per_kg": 75,
            "max_single_dose_per_kg": 15,
            "min_age_months": 3,
            "notes": "Not recommended under 3 months without medical advice.",
        },
        "renal_adjustment": "No adjustment needed for mild-moderate impairment. Extend interval to 6h if CrCl < 10 mL/min.",
        "hepatic_adjustment": "Max 2g/day in hepatic impairment or chronic alcohol use.",
    },
    "acetaminophen": {"_alias": "paracetamol"},
    "ibuprofen": {
        "generic_name": "ibuprofen",
        "available_strengths": [100, 200, 400, 600, 800],
        "unit": "mg",
        "adult": {
            "standard_dose": 400,
            "dose_range": [200, 800],
            "frequency_hours": 6,
            "min_frequency_hours": 4,
            "max_daily_dose": 3200,
            "max_single_dose": 800,
            "max_doses_per_day": 4,
            "route": "oral",
            "notes": "Take with food. OTC max is 1200mg/day. Prescription max is 3200mg/day.",
        },
        "pediatric": {
            "dose_per_kg": 10,
            "dose_range_per_kg": [5, 10],
            "frequency_hours": 6,
            "min_frequency_hours": 6,
            "max_daily_dose_per_kg": 40,
            "max_single_dose_per_kg": 10,
            "min_age_months": 6,
            "notes": "Not recommended under 6 months.",
        },
        "renal_adjustment": "Avoid if CrCl < 30 mL/min. Use with caution if CrCl 30-60 mL/min.",
        "hepatic_adjustment": "Use with caution. Avoid in severe hepatic impairment.",
    },
    "amoxicillin": {
        "generic_name": "amoxicillin",
        "available_strengths": [125, 250, 500, 875],
        "unit": "mg",
        "adult": {
            "standard_dose": 500,
            "dose_range": [250, 875],
            "frequency_hours": 8,
            "min_frequency_hours": 8,
            "max_daily_dose": 3000,
            "max_single_dose": 1000,
            "max_doses_per_day": 3,
            "route": "oral",
            "notes": "875mg q12h or 500mg q8h for standard infections. Higher doses for severe infections.",
        },
        "pediatric": {
            "dose_per_kg": 25,
            "dose_range_per_kg": [20, 45],
            "frequency_hours": 8,
            "min_frequency_hours": 8,
            "max_daily_dose_per_kg": 90,
            "max_single_dose_per_kg": 45,
            "min_age_months": 0,
            "notes": "High dose (80-90mg/kg/day) for otitis media or pneumonia.",
        },
        "renal_adjustment": "CrCl 10-30: 250-500mg q12h. CrCl <10: 250-500mg q24h.",
        "hepatic_adjustment": "No adjustment needed.",
    },
    "metformin": {
        "generic_name": "metformin hydrochloride",
        "available_strengths": [500, 850, 1000],
        "unit": "mg",
        "adult": {
            "standard_dose": 500,
            "dose_range": [500, 1000],
            "frequency_hours": 12,
            "min_frequency_hours": 8,
            "max_daily_dose": 2550,
            "max_single_dose": 1000,
            "max_doses_per_day": 3,
            "route": "oral",
            "notes": "Start 500mg BID with meals. Titrate weekly by 500mg. Take with food to reduce GI side effects.",
        },
        "pediatric": {
            "dose_per_kg": 10,
            "dose_range_per_kg": [10, 25],
            "frequency_hours": 12,
            "min_frequency_hours": 12,
            "max_daily_dose_per_kg": 50,
            "max_single_dose_per_kg": 25,
            "min_age_months": 120,
            "notes": "Approved for children ≥10 years. Start 500mg BID.",
        },
        "renal_adjustment": "eGFR 30-45: max 1000mg/day. eGFR <30: contraindicated.",
        "hepatic_adjustment": "Avoid — risk of lactic acidosis.",
    },
    "atorvastatin": {
        "generic_name": "atorvastatin calcium",
        "available_strengths": [10, 20, 40, 80],
        "unit": "mg",
        "adult": {
            "standard_dose": 20,
            "dose_range": [10, 80],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose": 80,
            "max_single_dose": 80,
            "max_doses_per_day": 1,
            "route": "oral",
            "notes": "Take once daily, any time of day. Start 10-20mg for most patients. 40-80mg for high CV risk.",
        },
        "pediatric": {
            "dose_per_kg": 0,
            "dose_range_per_kg": [0, 0],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose_per_kg": 0,
            "max_single_dose_per_kg": 0,
            "min_age_months": 120,
            "notes": "10-17 years: 10mg/day, max 20mg/day. Not weight-based — use fixed doses.",
        },
        "renal_adjustment": "No adjustment needed.",
        "hepatic_adjustment": "Contraindicated in active liver disease or unexplained persistent ALT elevation.",
    },
    "lisinopril": {
        "generic_name": "lisinopril",
        "available_strengths": [2.5, 5, 10, 20, 30, 40],
        "unit": "mg",
        "adult": {
            "standard_dose": 10,
            "dose_range": [2.5, 40],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose": 80,
            "max_single_dose": 40,
            "max_doses_per_day": 1,
            "route": "oral",
            "notes": "Start 10mg QD for hypertension. 5mg for heart failure. Titrate every 2-4 weeks.",
        },
        "pediatric": {
            "dose_per_kg": 0.07,
            "dose_range_per_kg": [0.07, 0.6],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose_per_kg": 0.6,
            "max_single_dose_per_kg": 0.6,
            "min_age_months": 72,
            "notes": "Children ≥6 years: start 0.07mg/kg/day (max 5mg). Max 0.6mg/kg/day (max 40mg).",
        },
        "renal_adjustment": "CrCl 10-30: start 2.5-5mg/day. CrCl <10: start 2.5mg/day.",
        "hepatic_adjustment": "No specific adjustment, but monitor closely.",
    },
    "omeprazole": {
        "generic_name": "omeprazole",
        "available_strengths": [10, 20, 40],
        "unit": "mg",
        "adult": {
            "standard_dose": 20,
            "dose_range": [20, 40],
            "frequency_hours": 24,
            "min_frequency_hours": 12,
            "max_daily_dose": 40,
            "max_single_dose": 40,
            "max_doses_per_day": 2,
            "route": "oral",
            "notes": "Take 30 min before breakfast. GERD: 20mg QD for 4-8 weeks. Ulcer: 40mg QD.",
        },
        "pediatric": {
            "dose_per_kg": 1,
            "dose_range_per_kg": [0.7, 3.3],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose_per_kg": 3.3,
            "max_single_dose_per_kg": 3.3,
            "min_age_months": 12,
            "notes": "1-16 years: 5-20mg based on weight. <10kg: 5mg, 10-20kg: 10mg, ≥20kg: 20mg.",
        },
        "renal_adjustment": "No adjustment needed.",
        "hepatic_adjustment": "Max 20mg/day in severe hepatic impairment.",
    },
    "amlodipine": {
        "generic_name": "amlodipine besylate",
        "available_strengths": [2.5, 5, 10],
        "unit": "mg",
        "adult": {
            "standard_dose": 5,
            "dose_range": [2.5, 10],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose": 10,
            "max_single_dose": 10,
            "max_doses_per_day": 1,
            "route": "oral",
            "notes": "Start 5mg QD. Elderly or hepatic impairment: start 2.5mg. Max 10mg/day.",
        },
        "pediatric": {
            "dose_per_kg": 0.1,
            "dose_range_per_kg": [0.05, 0.3],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose_per_kg": 0.3,
            "max_single_dose_per_kg": 0.3,
            "min_age_months": 72,
            "notes": "6-17 years: 2.5-5mg QD.",
        },
        "renal_adjustment": "No adjustment needed.",
        "hepatic_adjustment": "Start 2.5mg/day. Titrate slowly.",
    },
    "warfarin": {
        "generic_name": "warfarin sodium",
        "available_strengths": [1, 2, 2.5, 3, 4, 5, 6, 7.5, 10],
        "unit": "mg",
        "adult": {
            "standard_dose": 5,
            "dose_range": [1, 10],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose": 10,
            "max_single_dose": 10,
            "max_doses_per_day": 1,
            "route": "oral",
            "notes": "Highly individualized. Start 2-5mg/day. Adjust based on INR (target 2.0-3.0 for most indications). Monitor INR frequently.",
        },
        "pediatric": {
            "dose_per_kg": 0.2,
            "dose_range_per_kg": [0.05, 0.34],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose_per_kg": 0.34,
            "max_single_dose_per_kg": 0.34,
            "min_age_months": 0,
            "notes": "INR-guided dosing. Day 1: 0.2mg/kg (max 10mg). Subsequent: adjust per INR.",
        },
        "renal_adjustment": "No specific adjustment, but increased bleeding risk. Monitor INR closely.",
        "hepatic_adjustment": "Reduced dose needed. Enhanced response to warfarin. Monitor INR very closely.",
    },
    "aspirin": {
        "generic_name": "aspirin (acetylsalicylic acid)",
        "available_strengths": [75, 81, 100, 162.5, 325, 500, 650],
        "unit": "mg",
        "adult": {
            "standard_dose": 325,
            "dose_range": [75, 650],
            "frequency_hours": 4,
            "min_frequency_hours": 4,
            "max_daily_dose": 4000,
            "max_single_dose": 1000,
            "max_doses_per_day": 6,
            "route": "oral",
            "notes": "Analgesic: 325-650mg q4-6h. Cardioprotective: 75-100mg QD. Anti-inflammatory: 3.6-5.4g/day in divided doses.",
        },
        "pediatric": {
            "dose_per_kg": 10,
            "dose_range_per_kg": [10, 15],
            "frequency_hours": 4,
            "min_frequency_hours": 4,
            "max_daily_dose_per_kg": 90,
            "max_single_dose_per_kg": 15,
            "min_age_months": 192,
            "notes": "AVOID in children <16 due to Reye's syndrome risk. Only use if specifically indicated (e.g., Kawasaki disease).",
        },
        "renal_adjustment": "Avoid if CrCl <10. Use with caution in renal impairment.",
        "hepatic_adjustment": "Avoid in severe hepatic impairment.",
    },
    "azithromycin": {
        "generic_name": "azithromycin",
        "available_strengths": [250, 500, 600],
        "unit": "mg",
        "adult": {
            "standard_dose": 500,
            "dose_range": [250, 500],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose": 500,
            "max_single_dose": 500,
            "max_doses_per_day": 1,
            "route": "oral",
            "notes": "Day 1: 500mg, then 250mg QD for 4 days (Z-pack). Or 500mg QD for 3 days.",
        },
        "pediatric": {
            "dose_per_kg": 10,
            "dose_range_per_kg": [5, 12],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose_per_kg": 12,
            "max_single_dose_per_kg": 12,
            "min_age_months": 6,
            "notes": "Day 1: 10mg/kg (max 500mg), then 5mg/kg/day (max 250mg) for 4 days.",
        },
        "renal_adjustment": "No adjustment needed.",
        "hepatic_adjustment": "Use with caution in significant hepatic impairment.",
    },
    "cetirizine": {
        "generic_name": "cetirizine hydrochloride",
        "available_strengths": [5, 10],
        "unit": "mg",
        "adult": {
            "standard_dose": 10,
            "dose_range": [5, 10],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose": 10,
            "max_single_dose": 10,
            "max_doses_per_day": 1,
            "route": "oral",
            "notes": "Take once daily. May cause drowsiness.",
        },
        "pediatric": {
            "dose_per_kg": 0.25,
            "dose_range_per_kg": [0.125, 0.25],
            "frequency_hours": 24,
            "min_frequency_hours": 12,
            "max_daily_dose_per_kg": 0.5,
            "max_single_dose_per_kg": 0.25,
            "min_age_months": 6,
            "notes": "6-23 months: 2.5mg QD. 2-5 years: 2.5mg BID or 5mg QD. ≥6 years: 5-10mg QD.",
        },
        "renal_adjustment": "CrCl <30: 5mg QD.",
        "hepatic_adjustment": "5mg QD recommended.",
    },
    "losartan": {
        "generic_name": "losartan potassium",
        "available_strengths": [25, 50, 100],
        "unit": "mg",
        "adult": {
            "standard_dose": 50,
            "dose_range": [25, 100],
            "frequency_hours": 24,
            "min_frequency_hours": 12,
            "max_daily_dose": 100,
            "max_single_dose": 100,
            "max_doses_per_day": 2,
            "route": "oral",
            "notes": "Start 50mg QD. Volume-depleted patients: start 25mg. Max 100mg QD or 50mg BID.",
        },
        "pediatric": {
            "dose_per_kg": 0.7,
            "dose_range_per_kg": [0.7, 1.4],
            "frequency_hours": 24,
            "min_frequency_hours": 24,
            "max_daily_dose_per_kg": 1.4,
            "max_single_dose_per_kg": 1.4,
            "min_age_months": 72,
            "notes": "6-16 years: 0.7mg/kg/day (max 50mg), up to 1.4mg/kg/day (max 100mg).",
        },
        "renal_adjustment": "No adjustment needed. Not recommended in severe renal impairment with diabetes.",
        "hepatic_adjustment": "Start 25mg QD. Consider lower doses.",
    },
    "prednisolone": {
        "generic_name": "prednisolone",
        "available_strengths": [5, 10, 15, 20, 25],
        "unit": "mg",
        "adult": {
            "standard_dose": 40,
            "dose_range": [5, 60],
            "frequency_hours": 24,
            "min_frequency_hours": 12,
            "max_daily_dose": 80,
            "max_single_dose": 60,
            "max_doses_per_day": 4,
            "route": "oral",
            "notes": "Highly variable by indication. Asthma exacerbation: 40-60mg/day for 5-7 days. Taper for long-term use >2 weeks.",
        },
        "pediatric": {
            "dose_per_kg": 1,
            "dose_range_per_kg": [0.5, 2],
            "frequency_hours": 24,
            "min_frequency_hours": 12,
            "max_daily_dose_per_kg": 2,
            "max_single_dose_per_kg": 2,
            "min_age_months": 0,
            "notes": "Asthma: 1-2mg/kg/day (max 60mg) for 3-5 days. Croup: 1mg/kg single dose.",
        },
        "renal_adjustment": "No specific adjustment.",
        "hepatic_adjustment": "Prednisolone preferred over prednisone in liver disease (no hepatic conversion needed).",
    },
}


def get_dosing(drug_name: str) -> dict | None:
    key = drug_name.lower().strip()
    entry = DOSING_REFERENCE.get(key)
    if entry and "_alias" in entry:
        entry = DOSING_REFERENCE.get(entry["_alias"])
    return entry


def list_available_drugs() -> list[str]:
    return [k for k, v in DOSING_REFERENCE.items() if "_alias" not in v]
